[package]

name = "redlock-async"
version = "0.0.4"
authors = [
  "Jan-Erik Rediger <badboy@archlinux.us>",
  "Romain Boces <bocesr@gmail.com>",
  "hexcowboy <hex@cowboy.dev",
]

keywords = ["distributed", "locking", "dls", "redis", "redlock"]
description = "Implementation of the distributed locking mechanism built on top of Async Redis"

homepage = "https://github.com/hexcowboy/redlock-async-rs"
repository = "https://github.com/hexcowboy/redlock-async-rs"

license = "BSD-3-Clause"
readme = "README.md"
edition = "2021"

[dependencies]
redis = { version = "0.21.6", features = ["async-std-comp"] }
tokio = { version = "1.21.1", features = ["rt", "time"] }
rand = "0.8.5"
futures = "0.3.24"

[dev-dependencies]
once_cell = "1.15"
testcontainers = "0.14"
anyhow = "1.0"
tokio = { version = "1.21.1", features = ["macros"] }
tokio-test = "0.4"
